#!/bin/bash

# handle args
SCRIPT_ROOT=$(dirname "$(readlink -f $0)")
. $SCRIPT_ROOT/shflags
DEFINE_string 'src' '' 'SeewoOS image path.' 's'
DEFINE_string 'dst' '' 'USB device path.' 'd'

FLAGS "$@" || exit 1
eval set -- "${FLAGS_ARGV}"
# end handle args

echo Installing $FLAGS_src to $FLAGS_dst
pv -preb $FLAGS_src | sudo dd of=$FLAGS_dst bs=32M iflag=fullblock oflag=dsync

